### ISSUE TITLE
Doesn't work at all with Volto 17

### ISSUE THREAD

**Issue by kenmanheimer** [eea/volto-banner#30]
This does not seem to work at all with recent versions of Volto. I've been trying most recently with Volto 17.6.1 and Plone 6.0.8, but also earlier versions of Volto 17, with no success.

I used it early when I was trying Volto, but I don't recall what the versions were.

**Comment by avoinea** [comment]
@kenmanheimer Thank you for your report. Did you try it as described here: https://github.com/eea/volto-banner#try-volto-banner-with-docker

Indeed, we are still on Volto 16.x, but most of the EEA Volto Add-ons should work without issues, or with minor changes on Volto 17+. 

A PR would be appreciated :wink:

**Comment by kenmanheimer** [comment]
The problem was my mistake, I wasn't getting the backend addon to install properly. I now have it fully operational with Volto 17.6.1. Sorry about the false alarm!
